[versions]
agp = "8.2.2"
anychartAndroid = "1.1.5"
firebaseAuth = "22.3.1"
firebaseFirestore = "24.10.1"
firebaseStorage = "20.3.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
activity = "1.8.2"
constraintlayout = "2.1.4"
materialVersion = "1.11.0"
multidex = "1.0.3"

fragment = "1.6.2"
lifecycleLivedataKtx = "2.7.0"
lifecycleViewmodelKtx = "2.7.0"
playServicesMaps = "18.2.0"
legacySupportV4 = "1.0.0"
googleAndroidLibrariesMapsplatformSecretsGradlePlugin = "2.0.1"

[libraries]
anychart = { module = "com.github.AnyChart:AnyChart-Android", version.ref = "anychartAndroid" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore" }
firebase-storage = { module = "com.google.firebase:firebase-storage", version.ref = "firebaseStorage" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1100 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
multidex = { module = "com.android.support:multidex", version.ref = "multidex" }

fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
googleAndroidLibrariesMapsplatformSecretsGradlePlugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "googleAndroidLibrariesMapsplatformSecretsGradlePlugin" }


